// Mocks generated by Mockito 5.4.5 from annotations
// in dash_code/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dash_code/features/home_tasks/data/data_sources/local_data_source.dart'
    as _i3;
import 'package:dash_code/features/home_tasks/data/models/task_model.dart'
    as _i5;
import 'package:dash_code/features/home_tasks/domain/entities/task.dart' as _i7;
import 'package:dash_code/features/home_tasks/domain/repositories/task_repository.dart'
    as _i6;
import 'package:dash_code/features/home_tasks/presentation/cubit/task_cubit.dart'
    as _i8;
import 'package:dash_code/features/home_tasks/presentation/cubit/task_state.dart'
    as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskState_0 extends _i1.SmartFake implements _i2.TaskState {
  _FakeTaskState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalTaskSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalTaskSource extends _i1.Mock implements _i3.LocalTaskSource {
  MockLocalTaskSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TaskModel>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i4.Future<List<_i5.TaskModel>>.value(
              <_i5.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i5.TaskModel>>);

  @override
  _i4.Future<void> saveTasks(List<Map<String, dynamic>>? tasksJson) =>
      (super.noSuchMethod(
            Invocation.method(#saveTasks, [tasksJson]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i6.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.Task>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i4.Future<List<_i7.Task>>.value(<_i7.Task>[]),
          )
          as _i4.Future<List<_i7.Task>>);

  @override
  _i4.Future<void> addTask(_i7.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateTask(_i7.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TaskCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskCubit extends _i1.Mock implements _i8.TaskCubit {
  MockTaskCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTaskState_0(this, Invocation.getter(#state)),
          )
          as _i2.TaskState);

  @override
  _i4.Stream<_i2.TaskState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.TaskState>.empty(),
          )
          as _i4.Stream<_i2.TaskState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadTasks() =>
      (super.noSuchMethod(
            Invocation.method(#loadTasks, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addTask(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [title]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateTask(_i7.Task? updatedTask) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [updatedTask]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleComplete(_i7.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#toggleComplete, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void searchTasks(String? query) => super.noSuchMethod(
    Invocation.method(#searchTasks, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSearch() => super.noSuchMethod(
    Invocation.method(#clearSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.TaskState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i2.TaskState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
