buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Google Services plugin dependency for Firebase configuration
        classpath 'com.google.gms:google-services:4.4.2'
        // Firebase Crashlytics plugin to upload crash report mapping files
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.3'
        // Firebase Performance Monitoring plugin dependency (version as recommended or check Firebase docs for the latest)
        classpath 'com.google.firebase:perf-plugin:1.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

// Configure subprojects to use a common build directory structure
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// Ensure subprojects depend on the evaluation of the app module
subprojects {
    project.evaluationDependsOn(":app")
}

// Register a clean task to remove the build directory
tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
